### ISSUE TITLE
itunes

### ISSUE THREAD

**Issue by PANOSGRECIA1984** [naldogomes/music-search#3]
MY FRIEND THIS IS FOR SEARCHING MUSIC SONGS AND ALBUMS?AND IF YES,PLEASE COULD YOU MAKE A WEB VERSION?I AM BEGGING YOU MAN

**Comment by PANOSGRECIA1984** [comment]
please man answer me!!!

**Comment by naldogomes** [comment]
Hello @PANOSGRECIA1984, yes it's for searching songs and albums and actually this is a web version already!

**Comment by PANOSGRECIA1984** [comment]
wowwwwwwwwwwwwwww....mannnnnnnnnnnn the link pleaseeeeeeeeeeeeeeee???????????

**Comment by PANOSGRECIA1984** [comment]
@naldogomes MY FRIEND I HAVE NO IDEA FROM PROGRAMMING AND DEVELOPING!!!PLEASE CAN YOU TELL ME THE WEB?OR IF YOU WANT CAN YOU ENTER WITH TEAMVIEWER TO MY COMPUTER AND MAKE IT FOR ME?I AM BEGGING YOU DUDE!!!

**Comment by naldogomes** [comment]
@PANOSGRECIA1984 this is a web version but it's not released online. What you can do is to follow the instructions on README to run it on your pc.

**Comment by PANOSGRECIA1984** [comment]
MY FRIEND I KNOW BUT I CANT UNDERSTANDDDDDDDDDDD...I DONT KNOW HOW T O DO IT!!!CAN YOU MAKE IT FOR ME WITH TEAMVIEWER?I WILL PRECIATE IT SO MUCHHHHHHHHHH

**Comment by naldogomes** [comment]
I'm sorry, I can't. Maybe I'll release it later!
Thanks for commenting, I'm closing the issue!
